name: Update Custom Stats
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Download Stats Card
        run: |
          curl -s "https://github-stats-extended.vercel.app/api?username=shadow-x78&show_icons=true&theme=github_dark&hide_border=true&bg_color=0a0a0a&title_color=CC0000&icon_color=CC0000&text_color=666666&ring_color=CC0000&custom_title=GitHub+Stats&count_private=true&include_all_commits=true" -o github-stats.svg
          
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-stats.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update GitHub Stats" && git push)
